### ISSUE TITLE
Regularization Tuning

### ISSUE THREAD

**Issue by mattdias96** [icc2115/Neural-GC#10]
Hey! Do you have any advice on finding the optimal regularization parameter for the cMLP? For my dataset, I had  to increase the lambda and lambda_ridge parameters a lot to get Granger Causal coefficients near zero and was a bit concerned. Should I evaluate the model on the lower loss achievable during training or set up a test set?

**Comment by iancovert** [comment]
Hi, yes finding the right regularization is a bit tricky here. First, I would simplify things by setting `lam_ridge` to a fixed value (the particular value isn't too important, say `1e-2` or `1e-3`) and varying `lam` only. In our experiments, we didn't fixate on finding an optimal regularization parameter: we instead used a range of regularization strengths and examined how the Granger causal connections varied across the multiple models. 

If you want to find a sort of ideal regularization strength, I think what you're describing is reasonable (selecting the value based on out-of-sample fit). However, I would be a bit concerned about the best model selecting too many features (this is known to happen with lasso linear regression), so you may still want to consider checking the results with multiple regularization strengths.
